import {question,values,answer,radians} from './math.js';
const $=id=>document.getElementById(id);let unit='rad',current,selected=null,done=false,count=0,last='';
function angle(deg){return unit==='rad'?radians(deg):`${deg<0?'−':''}${Math.abs(deg)}°`;}
function renderFormula(){$('formula').innerHTML=`<span class="fn">${current.fn}</span> <span class="angle">(${angle(current.deg)})</span> = ?`;$('range').textContent=unit==='rad'?'−10π 〜 10π':'−1800° 〜 1800°';if(done)draw();}
for(const u of ['rad','deg'])$(u).onclick=()=>{unit=u;for(const v of ['rad','deg']){$(v).classList.toggle('active',v===u);$(v).setAttribute('aria-pressed',String(v===u));}renderFormula();};
function next(){do{current=question();}while(`${current.fn}:${current.deg}`===last);last=`${current.fn}:${current.deg}`;count++;selected=null;done=false;$('progress').textContent=`${String(count).padStart(2,'0')} 問目`;$('feedback').textContent='';$('check').hidden=false;$('check').disabled=true;$('next').hidden=true;$('empty').hidden=false;$('reveal').hidden=true;$('answers').replaceChildren();for(const value of values){const b=document.createElement('button');b.textContent=value;b.setAttribute('aria-pressed','false');b.onclick=()=>{selected=value;for(const button of $('answers').children){button.classList.toggle('selected',button===b);button.setAttribute('aria-pressed',String(button===b));}$('check').disabled=false;};$('answers').append(b);}renderFormula();}
$('check').onclick=()=>{if(selected===null||done)return;done=true;const ok=selected===current.value;$('feedback').className=ok?'feedback-good':'feedback-bad';$('feedback').textContent=ok?'✓ 正解！単位円でも確かめてみましょう。':`もう一歩！ 正しい答えは ${current.value} です。`;for(const b of $('answers').children){b.disabled=true;if(b.textContent===current.value)b.classList.add('correct');else if(b.textContent===selected)b.classList.add('wrong');}$('check').hidden=true;$('next').hidden=false;$('empty').hidden=true;$('reveal').hidden=false;draw();};
$('next').onclick=next;
function draw(){const norm=((current.deg%360)+360)%360,theta=norm*Math.PI/180,x=Math.cos(theta),y=Math.sin(theta),cx=200,cy=177,r=128,px=cx+x*r,py=cy-y*r;const sx=answer('cos',current.deg),sy=answer('sin',current.deg);const end=Math.min(norm,359.999)*Math.PI/180,ex=cx+34*Math.cos(end),ey=cy-34*Math.sin(end);
$('circle').innerHTML=`<defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#a7b5a1"/></marker></defs><circle cx="200" cy="177" r="128" fill="#fafcf7" stroke="#c6d4be" stroke-width="1.5"/><path d="M35 177H367 M200 333V20" stroke="#b6c3b0" marker-end="url(#arrow)"/><text x="372" y="182">x</text><text x="210" y="24">y</text><text x="331" y="194">1</text><text x="59" y="194">−1</text><text x="209" y="52">1</text><text x="208" y="315">−1</text><text x="185" y="194">O</text><path d="M200 177 L${px} 177 L${px} ${py} Z" fill="#e7efdf" opacity=".7"/><line x1="200" y1="177" x2="${px}" y2="177" stroke="#557f63" stroke-width="3"/><line x1="${px}" y1="177" x2="${px}" y2="${py}" stroke="#d19a64" stroke-width="3"/><line x1="${px}" y1="${py}" x2="200" y2="${py}" stroke="#d19a64" stroke-dasharray="4 4" opacity=".6"/><line x1="200" y1="177" x2="${px}" y2="${py}" stroke="#456c50" stroke-width="2"/>${norm?`<path d="M234 177 A34 34 0 ${norm>180?1:0} 0 ${ex} ${ey}" fill="none" stroke="#9aae80" stroke-width="2"/>`:''}<circle cx="${px}" cy="${py}" r="6" fill="#355f46" stroke="white" stroke-width="2"/><text x="${Math.max(30,Math.min(350,px+12))}" y="${py<70?py+22:py-12}" style="fill:#355f46;font-weight:700">P</text>`;
$('circle').setAttribute('aria-label',`角度 ${angle(current.deg)} の単位円。点 P の x 座標は ${sx}、y 座標は ${sy}。`);$('coordinates').textContent=`P = (${sx}, ${sy})`;
let explanation=`<strong>${angle(current.deg)} → ${angle(norm)}</strong><br>1 周の範囲で見ると、この点 P に重なります。<br>`;
if(current.fn==='tan')explanation+=`tan θ = y / x = (${sy}) / (${sx}) = <strong>${current.value}</strong>`;else explanation+=`${current.fn} θ は ${current.fn==='cos'?'x 座標（緑）':'y 座標（オレンジ）'}。<br>だから ${current.fn} θ = <strong>${current.value}</strong>`;
$('explanation').innerHTML=explanation;}
next();
