import test from 'node:test';import assert from 'node:assert/strict';
import {createSettlementTransaction,elo,initialRating,settleRating} from './rating-model.js';import {makeDeck,COUNTDOWN_MS,outcome} from './battle-engine.js';
function fixture(ranked=true){return {profiles:{a:{username:'Alice'},b:{username:'Bob'}},ratings:{a:initialRating(),b:initialRating()},rooms:{one:{from:'a',to:'b',fromName:'Alice',toName:'Bob',unit:'rad',ranked,status:'accepted',deck:makeDeck(),acceptedAt:1000}}};}
function finish(state,uid,base=7000){const room=state.rooms.one;room.moves??={};room.moves[uid]=Object.fromEntries(room.deck.map((q,i)=>[i,{seq:i,index:i,value:q.value,at:base+i}]));}
test('Eloは同格なら±16、格上への勝利ほど大きく、総和を保つ',()=>{assert.deepEqual(elo(1500,1500,1),{a:1516,b:1484,delta:16});assert.ok(elo(1300,1700,1).delta>16);const r=elo(1500,1600,.5);assert.equal(r.a+r.b,3100);assert.ok(r.delta>0);});
test('勝敗・レート・試合確定を一緒に更新し、再通知では二重加算しない',()=>{const s=fixture();finish(s,'a');assert.equal(settleRating(s,'one',9000),true);assert.equal(s.ratings.a.rating,1516);assert.equal(s.ratings.b.rating,1484);assert.equal(s.ratings.a.wins,1);assert.equal(s.ratings.b.losses,1);assert.equal(s.rooms.one.settlement.players.a.delta,16);const saved=structuredClone(s);assert.equal(settleRating(s,'one',9001),false);assert.deepEqual(s,saved);});
test('引き分け、開始後の降参、開始前の取消を区別する',()=>{const draw=fixture();finish(draw,'a');finish(draw,'b');settleRating(draw,'one',9000);assert.equal(draw.ratings.a.draws,1);assert.equal(draw.ratings.a.rating,1500);const loss=fixture();Object.assign(loss.rooms.one,{status:'abandoned',cancelledBy:'a',cancelledAt:1000+COUNTDOWN_MS});settleRating(loss,'one',9000);assert.equal(loss.ratings.b.wins,1);const early=fixture();Object.assign(early.rooms.one,{status:'abandoned',cancelledBy:'a',cancelledAt:1001});settleRating(early,'one',9000);assert.equal(early.ratings.a.games,0);assert.equal(early.rooms.one.settlement.rated,false);});
test('ゲスト・フレンドリー・未完了・不正な問題でレートを増やさない',()=>{const casual=fixture(false);finish(casual,'a');settleRating(casual,'one',9000);assert.equal(casual.ratings.a.games,0);const guest=fixture();delete guest.profiles.b;finish(guest,'a');settleRating(guest,'one',9000);assert.equal(guest.rooms.one.settlement.rated,false);const pending=fixture();assert.equal(settleRating(pending,'one',9000),false);const invalid=fixture();finish(invalid,'a');invalid.rooms.one.deck[0].value='wrong';assert.equal(settleRating(invalid,'one',9000),false);});
test('複数対戦を順次処理して双方のレートを失わず、遅れた降参は勝者を変えない',()=>{const s=fixture();s.rooms.two=structuredClone(s.rooms.one);finish(s,'a');Object.assign(s.rooms.one,{status:'abandoned',cancelledBy:'a',cancelledAt:8500});assert.equal(outcome(s.rooms.one).winner,'a');settleRating(s,'one',9000);const room=s.rooms.two;room.status='abandoned';room.cancelledBy='b';room.cancelledAt=8000;settleRating(s,'two',9001);assert.equal(s.ratings.a.games,2);assert.equal(s.ratings.b.games,2);assert.equal(s.ratings.a.rating+s.ratings.b.rating,3000);assert.equal(s.ratings.a.wins,2);});
test('Admin transactionの未取得nullで中断せず、サーバー値の再試行で確定する',()=>{const update=createSettlementTransaction('one',()=>9000);assert.equal(update(null),null);const s=fixture();finish(s,'a');assert.equal(update(s),s);assert.equal(s.rooms.one.settlement.rated,true);assert.equal(s.ratings.a.rating,1516);});
test('同じ相手とのレーティングは日本時間の1日5回まで',()=>{const s=fixture(),day=Date.UTC(2026,0,1,3);for(let i=1;i<=6;i++){const id=`match${i}`;s.rooms[id]=structuredClone(s.rooms.one);s.rooms[id].moves={};const room=s.rooms[id];room.moves.a=Object.fromEntries(room.deck.map((q,index)=>[index,{seq:index,index,value:q.value,at:7000+index}]));assert.equal(settleRating(s,id,day+i),true);assert.equal(room.settlement.rated,i<=5);if(i===5)assert.equal(room.settlement.pairDailyCount,5);if(i===6)assert.equal(room.settlement.reason,'daily_pair_limit');}assert.equal(s.ratings.a.games,5);assert.equal(s.ratings.b.games,5);});
